---
title: "Gut GVHD Pilot"
format: html
editor: visual
---

#### Data Loading

```{r}
library(Seurat)
install.packages("arrow")

matrix_dir <- "Data/SLV14/filtered_feature_bc_matrix"
spatial_dir <- "Data/SLV14/spatial"

counts <- Read10X(data.dir = matrix_dir)
slv14 <- CreateSeuratObject(counts, assay = "Spatial", project = "SLV14")
slv14 <- subset(slv14, subset = nCount_Spatial >= 50)

img <- Read10X_Image(image.dir = spatial_dir, image.name = "tissue_lowres_image.png")
img <- img[Cells(slv14)]
DefaultAssay(img) <- "Spatial"
slv14[["slice1"]] <- img  # attach image to the object

slv14
```

#### Data Quality Control

```{r}

slv14[["percent.mt"]] <- PercentageFeatureSet(slv14, pattern = "^MT-")

VlnPlot(slv14, features = c("nCount_Spatial", "nFeature_Spatial", "percent.mt"))
FeatureScatter(slv14, feature1 = "nCount_Spatial", feature2 = "nFeature_Spatial")

log_count <- log1p(slv14$nCount_Spatial)
med_count <- median(log_count)
mad_val_count <- mad(log_count)

count_lower_log <- (med_count - (mad_val_count*3))
count_upper_log <- (med_count + (mad_val_count*3))

count_lower <- expm1(count_lower_log)
count_upper <- expm1(count_upper_log)

log_feature <- log1p(slv14$nFeature_Spatial)
med_feature <- median(log_feature)
mad_val_feature <- mad(log_feature)

feature_lower_log <- (med_feature - (mad_val_feature*3))
feature_upper_log <- (med_feature + (mad_val_feature*3))

feature_lower <- expm1(feature_lower_log)
feature_upper <- expm1(feature_upper_log)

mt_upper = median(slv14$percent.mt) + (3 * mad(slv14$percent.mt))

dim(slv14)

slv14 <- subset(slv14, subset = nCount_Spatial < count_upper & nCount_Spatial > count_lower & nFeature_Spatial > feature_lower & nFeature_Spatial < feature_upper & percent.mt < mt_upper)

VlnPlot(slv14, features = c("nCount_Spatial", "nFeature_Spatial", "percent.mt"))
FeatureScatter(slv14, feature1 = "nCount_Spatial", feature2 = "nFeature_Spatial")

dim(slv14)
```

#### Data Normalization and Scaling

```{r}
slv14 <- SCTransform(slv14, assay = "Spatial", vars.to.regress = "percent.mt",
                     do.correct.umi = FALSE, conserve.memory = TRUE)
```

#### Data Dimension Reduction

```{r}
slv14 = RunPCA(slv14, assay = "SCT", npcs = 50)

ElbowPlot(slv14, ndims = 50)

slv14 <- FindNeighbors(slv14, reduction = "pca", dims = 1:15)
slv14 <- FindClusters(slv14)

slv14 <- RunUMAP(slv14, dims = 1:15)

DimPlot(slv14, reduction = "umap", label = TRUE)
SpatialDimPlot(slv14, label = TRUE, label.size = 3)


```
